language: objective-c  #1
osx_image: xcode10.1 #2
xcode_workspace: Example/BadasSwift.xcworkspace #3
xcode_scheme: BadasSwift-Example #4
xcode_sdk: iphonesimulator12.0
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XR #5
podfile: Example/Podfile
before_install:
  - gem install cocoapods --pre
  - cd Example/
  - pod install --repo-update
